### ISSUE TITLE
If the password doesn't meet password requirements, we need to re-render the form.

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-tck#247] opened 2016-04-16 00:27 UTC
https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling

> If the error is a password policy validation error, re-render the change password form and display the error to the user

**Comment by nbarbettini** [comment] 2016-04-16 16:43
Is this a dupe of #157?

**Comment by edjiang** [comment] 2016-04-16 16:50
Yes, couldn't find that earlier for some reason. Sorry!

**Closed as completed** 2016-04-16 16:50 UTC
Labels: forgot-password

**Comment by nbarbettini** [comment] 2016-04-16 17:02
Not a problem, there's a lot of issues :smile: 

FYI, I tagged the first stage (`/forgot`) as `forgot-password`, and the second change (`/change`) as `change-password`).

**Comment by edjiang** [comment] 2016-04-16 17:09
That's probably why
